### ISSUE TITLE
Uploading image attachments is broken

### ISSUE THREAD

**Issue by klausi** [XAMPPRocky/Mammut#47]
The upload photo example does not work with the mastodon.social server:

```
$ cargo run --example upload_photo
   Compiling mammut v0.12.0 (/home/klausi/workspace/Mammut)
    Finished dev [unoptimized + debuginfo] target(s) in 3.53s
     Running `target/debug/examples/upload_photo`
Enter the path to the photo you'd like to post: 
test.jpg
Error: Api(ApiError { error: None, error_description: None })
```

The response from the Mastodon server is:
```json
{
  "id": "14765098",
  "type": "unknown",
  "url": "https://mastodon.social/files/original/missing.png",
  "preview_url": "https://mastodon.social/files/small/missing.png",
  "remote_url": null,
  "text_url": "https://mastodon.social/media/_X2BWQQcaR_gAi5SfYU",
  "meta": null,
  "description": null,
  "blurhash": null
}
```

Why does the server return an unknown type?
How do we tell the server that this is just a JPG image it should accept?

**Comment by klausi** [comment]
Further debugging revealed that this was broken by #46 . When I revert that change the upload works again.

How can we debug the requests that are being sent to see what the difference is?

**Comment by XAMPPRocky** [comment]
@klausi Thank you for your issue! I've gone ahead added debug logging to requests. So if you now trigger debug level logging, mammut should should now print out the debug info of all requests and responses.

**Comment by klausi** [comment]
Thank you, managed to find the problem in the meantime, see #48
