### ISSUE TITLE
Release 0.13 to get file uploads improvements out

### ISSUE THREAD

**Issue by klausi** [XAMPPRocky/Mammut#51]
Problem: I need to depend on the dev version of this crate through github which is ugly. See https://github.com/klausi/mastodon-twitter-sync/blob/master/Cargo.toml

There have been some useful commits since 0.12, please release them.

Thanks!

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've now released version 0.13.0 which includes MediaBuilder and has updated dependencies.

**Comment by klausi** [comment]
Thank you so much!
